spring:
  application:
    name: SCW-PROJECT
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.99.38.203:3306/atcrowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
  redis:
    host: 192.168.31.128 #注册中心服务器的IP
    port: 6379

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true

server:
  port: 8000

swagger2:
  enable: true
feign:
  hystrix:
    enabled: true


